# Generated by Django 4.2.5 on 2023-10-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_book_average_rating_remove_book_total_ratings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrating',
            old_name='rating',
            new_name='ratings',
        ),
    ]
