# Generated by Django 4.2.5 on 2023-10-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_rating_bookrating_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ratings',
        ),
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
