# Generated by Django 4.2.5 on 2023-10-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_ratings_book_avg_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrating',
            old_name='ratings',
            new_name='rating',
        ),
    ]
