# Generated by Django 4.2.5 on 2023-09-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.book'),
        ),
    ]
