# Generated by Django 4.2.5 on 2023-10-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_shippingaddress_date_added_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
